services:
  - type: web
    name: expense-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: main.py
      - key: FLASK_ENV
        value: production